trigger:
- master
 
pool:
  vmImage: ubuntu-latest
 
variables:
  # 源代码扫描服务器地址
  SECURE_ANALYZERS_PREFIX: http://hya9.asls.space:21222
  # 源代码扫描userId
  USERID: 1499286106686955521
  # Git账号 请预先在源代码平台创建该账号
  GIT_ACCOUT: wujiacheng
  SCAP_API_IMAGE: $(SECURE_ANALYZERS_PREFIX)/oscap/sca-api/osca/oscaScanProject/myapis/putGitSvnProject
 
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "$(SCAP_API_IMAGE)"
      echo "$(USERID)"
      echo "$(System.TeamProject)"
      echo "$(Build.Repository.Uri)"
      echo "$(Build.SourceBranchName)"
      echo "$(GIT_ACCOUT)"
      echo "curl -k -H "Content-Type:application/json" -X POST $(SCAP_API_IMAGE) -d '{"userId":"$(USERID)","projectName":"$(System.TeamProject)","sourceUrl":"$(Build.Repository.Uri)","branch":"$(Build.SourceBranchName)","sourceType":1,"sourceAccount":"$(GIT_ACCOUT)"}'"
      curl -k -H "Content-Type:application/json" -X POST $(SCAP_API_IMAGE) -d '{"userId":"$(USERID)","projectName":"$(System.TeamProject)","sourceUrl":"$(Build.Repository.Uri)","branch":"$(Build.SourceBranchName)","sourceType":1,"sourceAccount":"$(GIT_ACCOUT)"}'